os:
  - linux
  
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm i

language: node_js

node_js:
  - "node"

notifications:
  email:
    on_success: never
    on_failure: change

git:
  depth: 10

branches:
  only:
    - master
